### 根据提供的 serviceId 获取实例信息
GET http://127.0.0.1:8000/ecommerce-nacos-client/hystrix/hystrix-command-annotation?serviceId=e-commerce-nacos-client
Content-Type: application/json

### 根据提供的 serviceId 获取实例信息
GET http://127.0.0.1:8000/ecommerce-nacos-client/hystrix/simple-hystrix-command?serviceId=e-commerce-nacos-client
Content-Type: application/json

### 根据提供的 serviceId 获取实例信息
GET http://127.0.0.1:8000/ecommerce-nacos-client/hystrix/hystrix-observable-command?serviceId=e-commerce-nacos-client
Content-Type: application/json

### 根据提供的 serviceId 获取实例信息
GET http://127.0.0.1:8000/ecommerce-nacos-client/hystrix/cache-hystrix-command?serviceId=e-commerce-nacos-client
Content-Type: application/json

### 根据提供的 serviceId 获取实例信息
GET http://127.0.0.1:8000/ecommerce-nacos-client/hystrix/cache-annotation-01?serviceId=e-commerce-nacos-client
Content-Type: application/json

### 根据提供的 serviceId 获取实例信息
GET http://127.0.0.1:8000/ecommerce-nacos-client/hystrix/cache-annotation-02?serviceId=e-commerce-nacos-client
Content-Type: application/json

### 根据提供的 serviceId 获取实例信息
GET http://127.0.0.1:8000/ecommerce-nacos-client/hystrix/cache-annotation-03?serviceId=e-commerce-nacos-client
Content-Type: application/json

### 根据提供的 serviceId 获取实例信息
GET http://127.0.0.1:8000/ecommerce-nacos-client/hystrix/request-merge
Content-Type: application/json

### 根据提供的 serviceId 获取实例信息
GET http://127.0.0.1:8000/ecommerce-nacos-client/hystrix/request-merge-annotation
Content-Type: application/json
